{% set name = "py-tools-ds" %}
{% set url_name = "py_tools_ds" %}
{% set version = "0.20.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ url_name }}-{{ version }}.tar.gz
  sha256: c745a3e540c2b75dbffc1783df4307707b0b9f80cc7f30de4f1138983f62d899

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - gdal >=2.1.0
    - numpy
    - pandas
    - pyproj >=2.5.0
    - python
    - shapely
    - spectral

test:
  imports:
    - py_tools_ds
    - py_tools_ds.io
    - py_tools_ds.geo
    - py_tools_ds.geo.raster.reproject

about:
  home: https://pypi.org/project/py-tools-ds/
  summary: A collection of Python tools by Daniel Scheffler.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mxr-conda
    - danschef
    - rluria14
    - ndmaxar
    - RyanHackney
