{% set name = "py-tools-ds" %}
{% set url_name = "py_tools_ds" %}
{% set version = "0.17.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ url_name }}-{{ version }}.tar.gz
  sha256: 3dfda4467685782fa5fdef1bbfec3d7cf0805f87cadfd7e9df58d48cab77021a

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - gdal >=2.1.0
    - geopandas
    - numpy
    - pandas
    - pyproj >=2.5.0
    - python
    - shapely
    - spectral

test:
  imports:
    - py_tools_ds
    - py_tools_ds.io
    - py_tools_ds.geo
    - py_tools_ds.geo.raster.reproject

about:
  home: https://pypi.org/project/py-tools-ds/
  summary: A collection of Python tools by Daniel Scheffler.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mxr-conda
    - danschef
    - rluria14
    - ndmaxar
    - RyanHackney
