{% set name = "py-tools-ds" %}
{% set url_name = "py_tools_ds" %}
{% set version = "0.23.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ url_name }}-{{ version }}.tar.gz
  sha256: 7bf06a709e97326b2e2d14efc5754b7e4f4d82cf27c0a3f0adb6bf2d5d85897c

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - setuptools
  run:
    - gdal >=3.8,<3.11
    - numpy
    - pandas
    - pyproj >=2.5.0
    - python
    - shapely
    - spectral

test:
  imports:
    - py_tools_ds
    - py_tools_ds.io
    - py_tools_ds.geo
    - py_tools_ds.geo.raster.reproject

about:
  home: https://pypi.org/project/py-tools-ds/
  summary: A collection of Python tools by Daniel Scheffler.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mxr-conda
    - danschef
    - rluria14
    - ndmaxar
    - RyanHackney
