{% set name = "py-tools-ds" %}
{% set url_name = "py_tools_ds" %}
{% set version = "0.19.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ url_name }}-{{ version }}.tar.gz
  sha256: f1d87618500f78eaf925682aa008b59e2029696ab35c72d59d4d4af14203dabe

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - gdal >=2.1.0
    - geopandas
    - numpy
    - pandas
    - pyproj >=2.5.0
    - python
    - shapely
    - spectral

test:
  imports:
    - py_tools_ds
    - py_tools_ds.io
    - py_tools_ds.geo
    - py_tools_ds.geo.raster.reproject

about:
  home: https://pypi.org/project/py-tools-ds/
  summary: A collection of Python tools by Daniel Scheffler.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mxr-conda
    - danschef
    - rluria14
    - ndmaxar
    - RyanHackney
